### ISSUE TITLE
Getting error messages on ros kinetic

### ISSUE THREAD

**Issue by stevensgeek41** [pal-robotics/gazebo_ros_link_attacher#12]
Does this package support ros kinetic? cos while catkin_make, I get the following error messages:

 _In member function ‘virtual void gazebo::GazeboRosLinkAttacher::Load(gazebo::physics::WorldPtr, sdf::ElementPtr)’:
/home/ssgeek41/ros_ws/src/gazebo_ros_link_attacher-melodic-devel/src/gazebo_ros_link_attacher.cpp:37:34: error: ‘class gazebo::physics::World’ has no member named ‘Physics’
     this->physics = this->world->Physics();
                                  ^
/home/ssgeek41/ros_ws/src/gazebo_ros_link_attacher-melodic-devel/src/gazebo_ros_link_attacher.cpp: In member function ‘bool gazebo::GazeboRosLinkAttacher::attach(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)’:
/home/ssgeek41/ros_ws/src/gazebo_ros_link_attacher-melodic-devel/src/gazebo_ros_link_attacher.cpp:67:40: error: ‘class gazebo::physics::World’ has no member named ‘ModelByName’
     physics::BasePtr b1 = this->world->ModelByName(model1);
                                        ^
/home/ssgeek41/ros_ws/src/gazebo_ros_link_attacher-melodic-devel/src/gazebo_ros_link_attacher.cpp:74:40: error: ‘class gazebo::physics::World’ has no member named ‘ModelByName’
     physics::BasePtr b2 = this->world->ModelByName(model2);
                                        ^
In file included from /opt/ros/kinetic/include/ros/ros.h:40:0,
                 from /home/ssgeek41/ros_ws/src/gazebo_ros_link_attacher-melodic-devel/src/gazebo_ros_link_attacher.cpp:2:
/home/ssgeek41/ros_ws/src/gazebo_ros_link_attacher-melodic-devel/src/gazebo_ros_link_attacher.cpp:96:100: error: ‘class gazebo::physics::Inertial’ has no member named ‘Mass’
 1 inertia is not NULL, for example, mass is: " << l1->GetInertial()->Mass())_

**Comment by awesomebytes** [comment]
The master branch should work on kinetic (the default one is melodic-devel).

**Comment by stevensgeek41** [comment]
Thanks, I didn't notice that. Will try later.

**Comment by stevensgeek41** [comment]
Yes, it builds cleanly.
