### ISSUE TITLE
No License specified

### ISSUE THREAD

**Issue by suhailps93** [pal-robotics/gazebo_ros_link_attacher#14]
It would be great if you could add a license to this package. It's a pretty great tool, thanks for developing this

**Comment by awesomebytes** [comment]
The license is BSD as in the package.xml: https://github.com/pal-robotics/gazebo_ros_link_attacher/blob/melodic-devel/package.xml#L11

**Comment by suhailps93** [comment]
Thankyou for the quick reply.
