### ISSUE TITLE
Build errors for gazebo 6

### ISSUE THREAD

**Issue by achim-k** [pal-robotics/gazebo_ros_link_attacher#2]
Hey, I assume you have build this only against gazebo 2? I get a lot of build errors for gazebo 6.6

**Comment by achim-k** [comment]
I was wrong, was just the missing C++11 compiler flags (see #3  )

**Comment by awesomebytes** [comment]
If I'm not wrong I also tried on gazebo 4.

And a friend from OSRF tried on gazebo 7.

No one tried on 6! (And the user base of this package is not very big :P)
