### ISSUE TITLE
About missing license information.

### ISSUE THREAD

**Issue by MilanPadhiyar027** [pal-robotics/gazebo_ros_link_attacher#22]
Hi,

Do we have any license information for this ROS package? If not then can you please add the license?

Thanks

**Comment by awesomebytes** [comment]
It's BSD as stated in the package.xml

https://github.com/pal-robotics/gazebo_ros_link_attacher/blob/melodic-devel/package.xml#L11

**Comment by MilanPadhiyar027** [comment]
Thank you for the information.
